### ISSUE TITLE
gaussian_process.py attempts to access param['pip']['pip']

### ISSUE THREAD

**Issue by mdav2** [CCQC/PES-Learn#12]
L:149 and L:238 of gaussian_process.py have the line:
`if params['pip']['pip']:`
Which causes a `TypeError`:
```
Traceback (most recent call last):
  File "modelbuild.py", line 16, in <module>
    X, y, Xscaler, yscaler =  gp.preprocess(params, gp.raw_X, gp.raw_y)
  File "/home/mmd01986/Dropbox/PES-Learn/peslearn/gaussian_process.py", line 149, in preprocess
    if params['pip']['pip']:
TypeError: 'bool' object is not subscriptable
```
I changed the line to `if params['pip']`, and that appears to work fine, but I also don't use `pip`s, so it could break something elsewhere. I don't know the codebase well enough to tell if that is an acceptable change.

**Comment by adabbott** [comment]
Hi Matt,

Thanks for opening an issue!
If I ventured a guess, this probably happened because I have restructured how the pip hyperparameter is defined several times in the past.  I assume this error probably occurred because you used an old version of PES-Learn to train a model and it produced the hyperparameters in one format, but since then the format was changed. As a result, when you use this old model, the hyperparameter syntax is incorrect. In whatever script you used to generate this error, try updating the definition of the pip hyperparameter in the `params` dict. I imagine it is currently `'pip': False` but it should be `'pip': {'pip': False}`  under the new syntax.

If this doesn't fix the problem, a minimal working example of the code that generated this error would be helpful.
