### ISSUE TITLE
Error: Co-linear atoms in an internal coordinate definition

### ISSUE THREAD

**Issue by 964922903** [CCQC/PES-Learn#16]
My input.dat file is as follows:
____________________________________________
C
C 1 R1
H 2 R2 1 A1
H 1 R3 2 A2 3 D1

R1 = [1.1, 1.55, 5]
R2 = [0.9, 1.60, 5]
A1 = [20.0, 180.0, 5]
R3 = [0.9, 1.60, 5]
A2 = [20.0, 180.0, 5]
D1 = [0.0, 180.0, 8]
_______________________________________

When i 'generate' data , Program error
show:
________________________________________

Error: Co-linear atoms in an internal coordinate definition
Traceback (most recent call last):
  File "/home/lcc/PES-Learn/peslearn/driver.py", line 30, in <module>
    config.generate_PES(template_obj)
  File "/home/lcc/PES-Learn/peslearn/configuration_space.py", line 205, in generate_PES
    self.generate_geometries()
  File "/home/lcc/PES-Learn/peslearn/configuration_space.py", line 81, in generate_geometries
    cart = self.mol.zmat2xyz()
  File "/home/lcc/PES-Learn/peslearn/molecule.py", line 213, in zmat2xyz
    self.atoms[i].local_axes = gth.get_local_axes(coords1, coords2, coords3)
  File "/home/lcc/PES-Learn/peslearn/geometry_transform_helper.py", line 40, in get_local_axes
    u23_x_u12 = unit_cross_product(u23, u12)
  File "/home/lcc/PES-Learn/peslearn/geometry_transform_helper.py", line 31, in unit_cross_product
    csc = sin**-1
ZeroDivisionError: 0.0 cannot be raised to a negative power
____________________________________________________________________

could u tell me how to deal with 
thank u

**Comment by adabbott** [comment]
Hi, thanks for raising an issue. I've seen this before, but it was fixed sometime in the past few months. Did you install PES-Learn from this CCQC repo recently? On the most up to date version of PES-Learn, running the following input:
```
C
C 1 R1
H 2 R2 1 A1
H 1 R3 2 A2 3 D1

R1 = [1.1, 1.55, 5]
R2 = [0.9, 1.60, 5]
A1 = [20.0, 180.0, 5]
R3 = [0.9, 1.60, 5]
A2 = [20.0, 180.0, 5]
D1 = [0.0, 180.0, 8]

mode = generate
```
with `python /path/to/peslearn/driver.py` works on my machine with the following output:
```
25000 internal coordinate displacements generated in 0.34649 seconds
Total displacements: 25000
Number of interatomic distances: 6
Warning: 5000 configurations had invalid Z-Matrices with 3 co-linear atoms, tossing them out! Use a dummy atom to prevent.
Geometry grid generated in 13.99 seconds
Removing symmetry-redundant geometries...  Redundancy removal took 0.08 seconds
Removed 11100 redundant geometries from a set of 20000 geometries
```

Here, the 5000 configurations with 4 co-linear atoms are simply removed instead of throwing an error. If you want to keep them, you can add a dummy atom (label it 'X') as a reference point in your Z-Matrix. Note you would have to design a new Z-matrix with adjusted coordinates.  

Here's a simple example of dummy atom usage, which scans the umbrella vibrational motion of the methyl radical CH3:
```
Scan over the umbrella motion of CH3
C
X 1 RDUM
H 1 R 2 A
H 1 R 2 A 3 D120
H 1 R 2 A 4 D120

RDUM   =  1.0
R      =  1.1
A    =  [40.0, 140.0, 21]
D120   =  120.0

mode = generate
```

Hope this helps.

**Comment by 964922903** [comment]
Thank you very much, the problem has been solved with your help.
